### ISSUE TITLE
Testing Bugs and Issues

### ISSUE THREAD

**Issue by Naomi-Nyama** [AppHatchery/Fabla-Front-end#101]
Bugs and Issue List after Testing Audio Diaries

1. Unsubmitted diary Bug
- A grey card appears on the screen when you don't submit the diary, click the close(x) button and return to the home screen and diary page(both calendar view and history view)
- 
![Screenshot_20231002-191452](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/f22dae0f-6cc0-4965-8f3a-f9566a966814)

- fixed in this pr: #99 
2. Failing to submit diary on Response summary page
- #71 
3. The continue bottom modal doesn't disappear when you delete a response
4. Audio recording:
- After you record audio, save it and delete the audio, when you try to record a new response and save it, it doesn't get saved and the audio card doesn't show up on the screen.
- The same scenario also happens when you record a short audio and try to save it 
- The scenario isn't always the same (sometimes when you follow those exact steps it works and sometimes is doesn't) 

@kennedylinzie and @Ikay-real may you please add more bugs and issues if I have left any out or you find more and feel free to add more content to the issues already here

@yago1994 here are the issues we talked about during the meeting

**Comment by Wiza-Munthali** [comment]
@yago1994 In regards to the failure to submit diary on response summary page, The upload function  seems to work fine but I did stumble upon an exception when cancelling a notification, the function for cancelling notification was cancelling the notification schedule instead of the notification in its entirety. So that bug has been fixed in the PR #107 and i was able to upload

**Comment by yago1994** [comment]
Adding more issues from latest build (PR #114 )

## Parameters
- Subject ID 0000
- Diary Done Today Tuesday 10th

## Issues
- Home page displays a diary completed on Wednesday instead of day of (Tuesday). I also saw this issue in a demo this morning. 
- Done Tag not appearing on the home page after the diary is completed (it does appear on the History page)
![IMG_644772A30F66-1](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/bbe8bb39-19dd-408f-beb7-54c2f349b0bf)

**Comment by yago1994** [comment]
Closing because issues have been either addressed or added to new tickets
