### ISSUE TITLE
UI Polish

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#12]
# Bugs!
1. Diary Summary button is aligned to the button of the text rather than constrained to top of page, with bigger fonts the whole thing slides down into the body of the page
2. ~~Diary icon should be unfilled when the user dismisses the Researcher's Note~~
3. ~~Animation after closing the button should go towards the left to signal the user that they went back (iOS)~~
4. ~~Tab bar overlay is indistinguishable from the background of the page (background should be #F4F4F4)~~
5. Color of Tab bar icons should be #537FF0 
6. ~~Remove view full transcript from diary card~~
7. ~~Redo, Record, Save buttons are a bit low, they interfere with the native scroll up functionality of the phone also too far out on the sides, the hover state hits the sides of the phone~~
8. ~~Remove the Transcript Toggle from Recording UI~~
10. ~~Record button does not work on iOS 🥲~~ 
(from here only Android)
12. ~~Native back button takes me back to home page from second diary prompt~~
13. ~~If delete all prompts from the entry, the My Response label remains (it should disappear)~~
14. ~~Overflow issues when audio card is expanded~~ included in #16 
15. ~~Redo triggers the recording to start automatically, it should erase the previous and wait for user confirmation~~
16. Delete tapping target feels very small, easy to miss
17. ~~I think we should only have one audio playing at a time and that also when you tap to close the card the audio stops (need design confirmation)~~ included in #16 

### The Striked out items have been worked on in the PR #11 

# Revisit design for:
- Resume button, feels like play but it continues recording
- Behavior of Continue Pop-up, is it necessary to have every time? It blocks the add a new response button. Additionally, Continue seems incorrect, something like 'Got it' seems to suit better the behavior of the pop-up
- What if user dismisses the recording screen by accident without having saved the recording? (propose to save it automatically
- Card deletion needs extra system visibility, user may delete multiple cards by accident because the 'next' card in line moves up with the detailed view expanded
- Card detail expansion and contraction, what should the tappable area of the card to prevent errors?
- How does the View Diary look and feel when you open a submitted diary?

**Comment by yago1994** [comment]
@JayceKongg here are the topics we talked about yesterday

**Comment by MorganGreenleaf-Emory** [comment]
Jayce updating Designs - Wait for updated designs and Yago will update tickets and assign

**Comment by JayceKongg** [comment]
Changes and thoughts about the questions (Figma link below): 

[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4027%3A28217&mode=design&t=Juxk1IGXU5qDe07n-1
](url)

1. Change the format of the ‘resume’ button.
2. I think it's fine to have the pop-up appear every time to let the user know that their responses have been saved successfully. (If the researcher doesn't have any notes on the page, the pop-up won't block the "Add a new response" button.)
3. First, the user needs to click the "Continue" button to proceed to the next question, so we can't use "Got It". However, we can use "Next Question". The problem is that in the final question, we need to change "Next question" to "Review summary" specifically.
4. We can not allow user to close the recording component by tapping outside of it.
5. Not an issue if we only enable user to expand one card at a time. (See below.)
6. Users can only expand one card at a time. When they tap to expand a card while another card is already expanded, the currently expanded card will contract and the new one will expand.
7. The interaction is similar to that on the summary page. When the user deletes the submitted diary, we delete the diary on the user's device, not on our end.

**Comment by Wiza-Munthali** [comment]
@yago1994 can you provide visuals for bug 1 & 12

**Comment by yago1994** [comment]
Visual for bug #1
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/b1bfa1c1-448c-4688-9bee-670b60986471)
The screen is responsive to large fonts but the banner height is not. Can we make that dynamic as well? That would solve the issue

bug #12 
We discussed it today and we suggested to:
- Increase the scroll window by the height of the 'Great' modal to allow the user to scroll downwards and interact with the 'Add a new response' button
- Move the 'Add a new response' to fit right below the audio diary card
