### ISSUE TITLE
Onboarding microphone request - tappable area in microphone to trigger request & title

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#139]
# Goal
Make the notification request more clear, it is not clear where to tap on the screen to enable the microphone. Usability Testing revealed that most people clicked on the microphone icon to 'enable' the microphone. 

## Tasks
- Adding a tapping target to the microphone icon to meet users expectations

**Comment by JayceKongg** [comment]
# Task 2 - Modify title
### Modify the title of the microphone test screen, because the previous title "Let's enable the microphone access" doesn't match the microphone test screen.

Screen 1 - ask for mic access: Please enable the microphone access 
Screen 2 - mic test: Great, let's test your microphone volume!

<img width="800" alt="Screenshot 2023-10-17 at 14 57 05" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ecff15e9-4f5b-4b3f-ae8b-1ad2533ccbb2">
