### ISSUE TITLE
Onboarding Notifications Access

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#17]
# Goal
Ask the user to enable notifications in the onboarding pages to allow the app to send reminders to complete the diaries

![Image](https://user-images.githubusercontent.com/16402216/264073428-40176ede-b651-40c4-928f-82b70ea34acf.png)

[Refer to Figma for updated design] https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=3230%3A12767&mode=design&t=yvvxn36z0Ddxd3MY-1

## Considerations
- To simplify development, let's use an image for the appearance of the notification request
![Image](https://user-images.githubusercontent.com/16402216/264073690-8093d03c-c70b-4d04-a801-9177d5ed0dcb.png)
- @JayceKongg can we think of the specific interaction for displaying the notification request? 1-2 seconds delay? User action?
- @JayceKongg what happens in the event users click don't allow notifications by accident or intentionally? We should consider the app's response in this state

**Comment by JayceKongg** [comment]
Design Update:

1. Notification Request Appearance: Since Android and IOS have different request formats and there are 3 buttons on the screen, users may not know where to click. Let's remove the request example on the reminder request screen. What do you think @yago1994? Also, there is an example with clear instructions on how to enable notification which I think is great, but they don't have the button on the bottom. If we use that, the design is not consistent with previous pages.

<img width="557" alt="Screenshot 2023-09-03 at 01 08 08" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/73f09215-7ed8-4355-902e-fc9f3358e54c">

Example:
![IMG_3245](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/52ac0509-a06b-437a-b3c4-9e35345fc090)
![IMG_3244](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/71384f8b-3487-4c37-99f2-98f06fe88208)

2. I think we can use the native interactions of Android and IOS. When the user taps the "allow notifications" button, the screen dims (0.5s) and a notification request appears.
Example:
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/c005f667-0d46-4961-9d45-6a4557098555

3. If the user dismisses the notification request, we push a popup on the home screen after the user completes the onboarding process. (Format and frequency of the pop-up TBD as we removed the Email, SMS, and phone call reminder.) Also, we can add a red dot around the "Settings" on the bottom nav bar. (TBD, since not sure if it's too annoying)

Example (Previous reminder setting pop-up page):
![Normal](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/22f9c77f-b235-4189-8cb3-2ac5a1253a09)

**Comment by yago1994** [comment]
@JayceKongg I agree. Let's have a clean page, no example image, with a button at the bottom of the page that triggers the notification request. 

Minor caveat, let's call the button 'Continue' rather than 'Allow notifications' in the case that users don't want to allow notifications. That way there won't be confusion as to the users flexibility (this does not apply to the microphone page where we DO need the microphone access)

If the user clicks 'Don't Allow' notifications in the pop-up, I suggest we have a bit of text appear on screen that prompts the user to turn them on in the Settings page at the phone level. I was thinking something like this could look good and minimal
![image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/894180d1-b033-43f7-947a-1bc22ac5c212)

Tapping on the underlined word would send the users to the Settings page in the same way that we would in the apps Settings page
