### ISSUE TITLE
Onboarding Microphone Access

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#18]
# Goal
To request access to the device's microphone

## Considerations
- Add the warning message when permission is denied (refer to image below)
- Change language to "Open Settings" in the button
- Route user to Settings page

##

Draft
![Image](https://user-images.githubusercontent.com/16402216/264087637-4c62e209-832c-4254-8ebf-30d4337a1d23.png)

## Considerations
- What visual artifacts can we use to inform the user that we need microphone access?
- How can users know right away the microphone is working without additional screens?
- How can users know that the microphone is not working correctly or picking up their voice? 
- How can users know that microphone permissions are not granted? 
- How can users know how to enable permissions if they did not enable them by mistake?

## Inspiration
There are standard interaction paradigms which tell the user the microphone is responding to their speech/sound that don't involve a lot of user action, mostly visual

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/d5ed8499-0234-444f-b851-ba9c5cbf7ac9

Permission Denied Message
- Appears right after user denies access, this can be the same for the notification request
- Style of message can be matching the app since this is not a native request anymore
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/22bc2902-b49f-44cd-9e77-f6a05d6f4824)

**Comment by JayceKongg** [comment]
Design Update:

Three alternatives for the microphone access user flow:
1. The microphone test is optional, the user needs to tap "start mic test" to start testing the mic. Or they can skip the test.
2 and 3. When the user provides microphone access, we automatically initiate a microphone test. The difference between alternative 2&3 is the UI of the volume (One is round [like mimi] and the other is square, no strong preference, we can discuss that later).

Thoughts: 
1. Auto mic test. It's good for us because it's more clear for the user to know that we can't access the microphone and the volume of their voice. If there's any issues happend about the microphone, it's easier to be identified from the microphone test. (I recommend this one).
2. Manual mic test. It's good for users because users have the control to either take the mic test or skip it.

1. Automatic microphone testing. This is good for us because users can be more aware of our inability to access the microphone and their volume. If there are any problems with the microphone, it is easier to recognize them with an auto microphone test. (I recommend this one).
2. Manual microphone test. This is good for users because the user has the option to take the microphone test or skip the test. (More user control, users feel comfortable with their privacy because we don't collect anything automatically)

Figma link: (Details TBD, like the dialogue)
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4167%3A17783&mode=design&t=ThazeOr3T3v5fZvM-1](url)

Alternative 1: 
<img width="1000" alt="Screenshot 2023-09-02 at 19 35 04" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4f22a997-ba4f-4798-baee-1f5073f57b9b">

Alternative 2: 
<img width="1000" alt="Screenshot 2023-09-02 at 19 35 19" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2dd795f6-b47a-4da3-baf1-72f683718b1b">

Alternative 3:
<img width="1000" alt="Screenshot 2023-09-02 at 19 35 26" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/58e864c7-b314-497b-b937-e6e3917a2d53">
