### ISSUE TITLE
Make Free Text Entry Component to diary flow

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#227]
# Goal
In addition to the regular long free response entries in Audio or Written format, we want to include a short text-entry response to questions like
1. What describes the location where you are RIGHT NOW? (e.g., work, school, home, restaurant, etc.) For your privacy please do NOT give your exact location. [FREE RESPONSE]
2. Just before you got this survey what were you doing? (e.g., “watching TV”, “eating lunch”, etc.) [FREE RESPONSE]

The expectation for these questions is to type a short phrase or a few words, not a long paragraph. 

## Task
- Make a component similar to the multiple choice, slider, etc,. type of questions that contains a text field

**Comment by yago1994** [comment]
@JayceKongg add screenshot here, made a quick mock in Figma

**Comment by JayceKongg** [comment]
### UI Design and interactions

The margins are the same as other components in the survey flow.
After typing, users type the "check" button to confirm.

- feft: default status
- right: active (input) status

<img width="836" alt="Screenshot 2024-04-09 at 20 40 03" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/fca67d3e-19a8-475c-89ff-bbcf6f33858a">

### Edge case: if the content is too long

The content of the card is scrollable, preferably automatically scrolling up when the content exceeds the screen size. **But we can let the user scroll up manually first**, because I don't think there are many users who enter too much information in the text input box.

<img width="363" alt="Screenshot 2024-04-09 at 20 41 36" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/f41f7b3d-c7db-4304-bc9b-186e9f4a622c">

**Comment by hopemadziakapita** [comment]
@yago1994 is there a minimum length of characters for these responses to be considered valid? or anything goes as long as the user has typed in something?

**Comment by yago1994** [comment]
> @yago1994 is there a minimum length of characters for these responses to be considered valid? or anything goes as long as the user has typed in something?

No minimum, just not an empty string
