### ISSUE TITLE
Bug on Time counter when diary end date is 11:59p

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#448]
Bug on countdown

## Steps to reproduce
- Test on experiment from Retool that has 23:59 as the deadline for the diary
- You can try PTEST
- ![Image](https://github.com/user-attachments/assets/28975267-cd3e-485d-8f91-3daa515956a5)

**Comment by Wiza-Munthali** [comment]
@yago1994 Could you please provide more context on the issue? Specifically, I would appreciate some details of the steps you took to cause this problem. I tried a diary with a deadline of 23:59, I'm using Experiment BMR1 because PTEST didn't have any diaries ending at 23:59

![image](https://github.com/user-attachments/assets/8922793a-3de4-4497-9e17-0d9df2cfabaa)

![IMG_1779](https://github.com/user-attachments/assets/b9cd159d-2173-40f0-b8e0-4568909ca96f)

**Comment by yago1994** [comment]
No problem.

I had the PTEST experiment have the daily diary end at 23:59 from Retool before, perhaps you can change it? There may be something specific about the configuration for that diary that’s causing this. Not urgent, I rather do a whole evaluation of diary end times before we dive here.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yago1994** [comment]
Probably an artifact due to manual time shifts
