### ISSUE TITLE
Text entry type questions have a bug where the keyboard is automatically dismissed

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#449]
# Bug
For a Text Entry type of question, when the user begins typing the keyboard is automatically dismissed with each key press.

## Steps to reproduce
- Open experiment PTEST and go to the text-entry type of questions (not the audio one!)

**Comment by Wiza-Munthali** [comment]
@yago1994 I was looking at this issue yesterday and there are two solutions to the problem;

1. When a user is presented with a text-only question, have the user respond through the same modal as the audio response. This solution is the least complex.
![image](https://github.com/user-attachments/assets/19e508f8-a1fc-4e3a-82ce-47b626dda412)

2. Rewrite how we save the answers, the current implementation is after the user selects or inputs an answer the app saves the selected/input answer into the database immediately that's why the keyboard and text field keep losing focus because the widgets are rebuilding after every answer (stroke of every key on the keyboard). If we are to rewrite the logic then the user will only be able to save the answers when they click on the "Next" button, caveat, if the user selects for example multiple choice answers and goes back or exits the survey the app will not save those answers and the user will have to reenter the answers. This solution is more complex and requires more effort.

**Comment by yago1994** [comment]
Sounds like option 1 is the easiest, could we have the modal be the default screen or we have to go through the two step process?
I just want to create some differentiation between audio and text based questions but if there’s no possibility then we can use the same widget for now.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
