### ISSUE TITLE
Late submissions

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#52]
# Goal
Diaries are not allowed to be submitted past 4am the day afterwards

## Considerations
- A new diary will be allowed for submission from 4a until 4a the following day

**Comment by yago1994** [comment]
@JayceKongg how are missed submissions handled in the Diaries tab?

**Comment by JayceKongg** [comment]
> 

We can add the tag 'Missed Diary' to the card. I want to keep the missed diaries in the 'Diary History' so users can know why and when they missed a diary, making the system transparent to users. (If the diary missing will impact their compensation, they might want to know that.)

![ListView](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/5f5c4a04-5b84-43f5-8c64-3523f9682f0f)

https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4356%3A46328&mode=design&t=CyAJE760psGMWz6p-1

**Comment by yago1994** [comment]
@JayceKongg the 'missed' tag is a bit small and people may 'miss' it (sorry for the pun). 
What about a more explicit state? Why should we allow the users to View? 

Also a couple thoughts, since they diary now is really long, what should we show in the question summary? 
<img width="344" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/6c057c07-aa24-46ec-bbd9-a4e539339cda">

**Comment by JayceKongg** [comment]
Here's the new design for the "history page". I deprioritized the CTA button to make it work better with the cards. Since I noticed that the calendar is already built into the app, we can use it as a filter to show the history of each day (It's easier to build, but not as flexible as the second interaction, see the Outlook calendar, I shared a screenshot video below). Also, the button in the upper right corner is used to display the list view, where we only show the history for the days included in the study.

Interaction alternative 1: Using the calendar as a filter.
<img width="1400" alt="Screenshot 2023-09-22 at 21 31 44" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/3c656875-e78d-4f87-96ef-d2ef79a06ea2">

Interaction alternative 2: When scrolling down, the calendar changes accordingly.
<img width="1400" alt="Screenshot 2023-09-22 at 21 31 58" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/13433

Screenshot video:
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/0d332245-f6cc-423b-a866-3edd14f34ce2
6047/e0fb8425-e44d-42af-b196-9b20d0c7ccca">

Figma:
https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4567%3A62158&mode=design&t=IsSDVivabksDOk8a-1

**Comment by yago1994** [comment]
@JayceKongg can you drop here which design we settled on for the Diary Tab after we talked yesterday? There's so many variants on Figma. Let's either use the MVP tab or make a new tab that contains the current design being discussed. The variants can be on other pages.

Also keep in mind the calendar being on the same page as the diaries is new design. Don't have time to implement that.

**Comment by JayceKongg** [comment]
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4627%3A18592&mode=design&t=CRYSwReWlAokHkSL-1](url)

This tap includes all the latest designs.

**Comment by JayceKongg** [comment]
For the diary (history) tab, we're going to use the previous design but change the labels to "ongoing", "missed" and "done". The content on the card will be a label (ongoing, missed or done) and Day x - Study Name (For the ongoing task, let's use the question where the user exit, if appliable). 

Screenshot:
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/332d35f1-9f9b-4a2f-92b5-e8a81f85ab0c)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ce6b4481-a865-482d-be57-ed0aef2c6386)

Lables:
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/a5672335-8d38-4eac-97a4-b5587d2fdac5)


Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4627%3A38808&mode=design&t=CRYSwReWlAokHkSL-1](url)

**Comment by yago1994** [comment]
Got it, this is clear! Making a ticket

**Comment by JayceKongg** [comment]
Add two tags for "ready to start" and "Awaiting Submission"

Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4541%3A46167&mode=design&t=Qv6UmVodHfh9YowZ-1
](url)

<img width="528" alt="Screenshot 2023-10-05 at 16 26 46" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4648c54b-b35f-4bce-bd70-3a1279ab6e27">
