### ISSUE TITLE
Study start

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#53]
# Goal
Determine when the participant will be starting the study.

All participants will begin the FULL study (12 days) on the closest Sunday to them (i.e. if today is 9/11 the study will begin 9/17).

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/7334dd50-6113-40a1-9153-c05dc860ba67)

## Considerations
- A subjectID-key file will determine if the participant begins 1. with the app or 2. with the survey
- ALL participants will install and open the app during the week (M - F)
- The expected study start should be saved in the app as a variable to reference in the future

## Tasks
1. Detect current date and populate a variable with the start date for the upcoming Sunday (add commented code to detect following Saturday; for the group that will start later)
2. Save variable in internal storage (this variable will be used in #50 to determine which prompt to display)

## Out of scope (for now)
- Expected study start will trigger reminder notifications for the study

**Comment by MorganGreenleaf-Emory** [comment]
@yago1994  Can you give an example of this subjectID-key file?

**Comment by yago1994** [comment]
This depends on the format we want to follow. 
Probably something like this:
{"subjectId": 1001, "branch": "survey", "branchId": 1}

**Comment by Wiza-Munthali** [comment]
@yago1994 ~~is there a reason why the data needs to be stored in a file(subjectID-key file)? My main concern is having multiple sources of truth where we have the app collecting its operating information for multiple sources~~ 

My bad I read the considerations wrong, I was assuming the subjectID file was a file we'd need to create in the application rather than a static file that will dictate what group of participants will start

**Comment by Wiza-Munthali** [comment]
@yago1994 @JayceKongg can we have a redesign of the avatar bubble message to reflect the new active dates



![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/42870528/32ad2c6c-4b20-4b16-8cc7-4c1a514f2398)
