### ISSUE TITLE
Empty states for Home screen and History screen

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#63]
# Goal
Add empty states to the home and diary pages when the user does not have any diaries due. This will match the user's expectations of how the app would respond to content.

## Considerations
- Home page should display the 'before' message until the diaries begin, then message should disappear
- Home page should display the 'end' message ever after the study is done (i.e. if you start on Sunday and end on Friday, after Friday the home page should always display that message)
- Diary page should display the 'before' message until the diaries have began, after that the message should _____

Home page
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/527d9b63-2985-4b07-bc02-5894c7741839)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/013216de-7011-45dd-83ef-880d84bc7c63)

Diary page
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/3619fd40-f7b5-407d-acb2-b19c3b26e24b)

##
# Previous Goal
Improve the user's experience when they first arrive to the home screen. Currently it displays an empty screen and the user may not know if the app has a bug since it looks like something should be there. I suggest we include empty states for all the screens that are not displaying anything until the study begins.

## Considerations
- This only needs to appear when the user arrives to the app but has no diaries present (because it's not the start date yet)
- Card content is dynamic, the date listed should be the Study date pulled from our saved data
- Display this message if date < start_date
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/a29cbb57-674d-440a-aaaa-fc6577ebc4a3)

## 

# Previous Goal
![Image](https://user-images.githubusercontent.com/16402216/267724215-8bbbfdfc-398b-437a-a4f3-e05c30830c1e.jpeg)

Home screen
- Study hasn't started state - i.e. we will see you on Sunday, nothing for you to do at the moment
- Study has ended state - 
- Propose to remove the Today's Diaries label until Diaries actually show up

Diaries
- Study hasn't started state - i.e. this is where your submitted diaries will go

**Comment by JayceKongg** [comment]
I tried two empty states for the home screen (tasks screen). We can keep the "Today's Tasks" label, but add hints under it. The first way is using a card says "No Tasks Today: Enjoy Your Free Time!!🍾". And the second one is using a mascot says the same thing. (See screenshots and the Figma file below).

I prefer the second one since it's more obvious than the first - A card there conveys that the user needs to do something, especially when they first see it. So using mascot could aviod that I think.

<img width="1000" alt="Screenshot 2023-09-23 at 00 33 07" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/3aa38a8d-a4e5-4b9f-9aac-e53913e9a60e">

Figma mockups:
https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4571%3A76461&mode=design&t=IsSDVivabksDOk8a-1

**Comment by JayceKongg** [comment]
Additionally, I have updated the calendar because participants are required to response consistently for 6 days.

The previous calendar was suitable for when participants could choose to do diaries at any time as long as they completed the required amount of responses (2x/week). Whereas for the Oct study, they could not do this. Therefore, I changed the calendar to a standard calendar like Outlook, Google Calendar, etc. Users can see when they need to do their responses and how much tasks they have left for the week.

**Comment by yago1994** [comment]
@JayceKongg can you provide the states for:
- Diary tab before study starts
- Home page after study ends

This task is going to be a polish item for next week

**Comment by JayceKongg** [comment]
Diary (History) tab before and after study dates:
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/c1f98127-b037-42d0-93a6-5017ee3bc8b0)
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4672%3A60748&mode=design&t=CRYSwReWlAokHkSL-1](url)

Home page after study ends:
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/9bae180a-bf67-4730-a944-ac18017072fd)
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4642%3A43912&mode=design&t=CRYSwReWlAokHkSL-1](url)

**Comment by yago1994** [comment]
@JayceKongg home page looks great 👌 I like the messaging on both states, it's calm while bubbly. I'll make a ticket for this and backlog.

The History Tab however looks very different than what we have right now. I think aiming for that in the future is good but we need a design for the October study. Can we use that card design with our current History tab design? How does it behave, does it disappear when you start?

**Comment by JayceKongg** [comment]
Update:

@yago1994, I replaced the calendar on the history page with the previous one. Now it's ready on Figma ⬇️. 
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4627%3A18592&mode=design&t=9JxbzT9m73xIqbw8-1](url)

<img width="1300" alt="Screenshot 2023-09-29 at 15 58 46" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2615e1be-b282-49e4-a340-a0853dbac033">

In addition to the calendar, I also update an empty status (card) when the user views the active dates during the study period. For example, the study period is June 8th through June 13th. The user is on Friday, June 6, and when they view the study for June 8th, we can display "You will see questions on the scheduled date."

<img width="321" alt="Screenshot 2023-09-29 at 16 01 49" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b593a189-d90c-41a9-9843-53fc8f0ed864">

@Wiza-Munthali I see your comment on Figma that we need a label for when the diary hasn't started yet. Can we use the empty cards I attached above?

<img width="474" alt="Screenshot 2023-09-29 at 16 03 51" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2ff8e914-44c0-43c1-925d-547aa6066ee6">

<img width="473" alt="Screenshot 2023-09-29 at 16 03 59" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/7cc76196-1375-4b82-9dcf-ce38d963d049">

**Comment by yago1994** [comment]
Wonderful, thank you @JayceKongg. Some follow ups:
- What is the behavior of that card once the user starts, does it disappear? (This may be easier for development to have less custom items)
- Rather than having a "this is a free day" after the user has finished the study, should we use a more custom messaging implying the study is finished?
- I think the issue Wiza refers to is having a 'tag' for a diary that hasn't been started. 'Ongoing' means that something is currently happening, so what he's asking for is for a tag for 'Ready to begin' or something like that

**Comment by JayceKongg** [comment]
Update simple illustrations that we can use in empty states.

<img width="944" alt="Screenshot 2023-10-03 at 13 31 47" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4d919820-d487-4e2b-b90b-6e3494041772">
<img width="224" alt="Screenshot 2023-10-03 at 13 31 55" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/6283951d-0f25-4af4-9f0f-d877ff1decd3">

Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4872%3A28258&mode=design&t=HWB8yfmGOTpbBH2h-1](url)

**Comment by JayceKongg** [comment]
Update: Calendar on the home screen and illustrations for empty states (before & after the study period).

The date (when the calendar and illustrations are displayed) is shown in the calendar at the top of the screenshot. The monthly calendar will be used for the history page.

(from left to right): before the start of the study, on the first study day, on the first study day but with the task completed, on the last study day, and after the study end date.

<img width="1600" alt="Screenshot 2023-10-03 at 21 11 02" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/772035aa-d031-4434-8595-b7018fdea1fe">

Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4893%3A26514&mode=design&t=xraK2FRhBf2o9Jmb-1](url)

**Comment by JayceKongg** [comment]
### Update: the calendar on the home page

1. **All dates in the calendar can be see-through now.**
2. **Remove the "Night owl? You can submit by 4 AM tomorrow" notification on the home page.** Will have a pop-up screen that contains the same information for first-time users.
3. **Replace the "notebook" icon with a "target" icon.** So I can cover two meanings: "X days left in the first study" and "X diaries left in this study".
<img width="488" alt="Screenshot 2023-10-05 at 17 31 19" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/a99907a2-e673-4c04-9259-492b5724b98a">
<img width="487" alt="Screenshot 2023-10-05 at 17 31 28" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/59706c25-aa0a-4a20-b894-8f8f13776552">

**For more comments about the calendar on the home page see the issue "Behavior for home page calendar view"** #60 

Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4940%3A40425&mode=design&t=Qv6UmVodHfh9YowZ-1](url)

<img width="1318" alt="Screenshot 2023-10-05 at 17 54 56" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4b67d3ce-ed86-41ea-8576-c51b90d34c09">

**Comment by JayceKongg** [comment]
### Update: the calendar on the history page

Since we plan to disable the calendar interaction on the history page, in the calendar view, the logic for cards and empty states is the same as on the main screen. The user can neither go back to view previous diaries nor view future research questions. Therefore, we only need 2 empty states like on the home page: before the start of the study and after the end of the study.

I proposed 3 alternatives for the 2 empty states:
1. Card. This one is more consistent with other diary cards.
2. Illustration. This requires less development work because we already have these illustrations on the main screen.
3. Leave it blank. I wouldn't recommend this one unless the illustration one is too complicated. It seems like something went wrong in the app.

Figma link: [https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4940%3A46034&mode=design&t=Qv6UmVodHfh9YowZ-1](url)

<img width="1184" alt="Screenshot 2023-10-05 at 18 36 51" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/5bc6f1ff-f8ad-4cb3-94cc-329edc06f6d7">
