### ISSUE TITLE
Diary Navigation - Remove Skip

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#80]
# Goal
User should be able to navigate back when doing a diary

## Tasks
- Incorporate back arrow at the base of the screen next to the Continue button
- Close button on the top left exits the flow
- [Old] Skip button on the right skips the question
- [New 10/06/23] Remove 'Skip' button from diary navigation

## To be determined
- Native navigation (top for iOS) vs bottom navigation (current discussion on #49 )

**Comment by yago1994** [comment]
@Naomi-Nyama can you add screenshots?

**Comment by Naomi-Nyama** [comment]
<img width="342" alt="Screenshot 2023-09-28 at 2 53 48 PM" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/780b5a01-41a4-432e-95c2-4f0e048f7600">
<img width="342" alt="Screenshot 2023-09-28 at 2 53 35 PM" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/f5f21b68-75fe-48ce-b4e6-ea4227f4edca">
<img width="342" alt="Screenshot 2023-09-28 at 2 53 19 PM" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/586907de-d8f1-4596-a586-ab38232e1533">

**Comment by yago1994** [comment]
Thanks @Naomi-Nyama !

@JayceKongg can you take a look at these? Naomi was able to get a navigation element at the base of the window as you suggested and was wondering on the implementation at the top of the page. 
- Do we want to have the 'x' and 'Skip' buttons at the top of the page? 
- Would users know what 'Skip' entails? 

Things to consider.
- It's unlikely people will skip a question, after all, this is a study where you "have to" answer the questions. Deprioritize.
- Back button is very important to preserve the user's freedom throughout the app so it should be prioritized
- Going back to home page is not a usability critical since there's nothing on the home page the user needs to access when they are doing the diary. However still necessary since we don't have a tab bar to let them clear out the navigation stack.

**Comment by JayceKongg** [comment]
> Thanks @Naomi-Nyama !
> 
> @JayceKongg can you take a look at these? Naomi was able to get a navigation element at the base of the window as you suggested and was wondering on the implementation at the top of the page.
> 
> * Do we want to have the 'x' and 'Skip' buttons at the top of the page?
> * Would users know what 'Skip' entails?
> 
> Things to consider.
> 
> * It's unlikely people will skip a question, after all, this is a study where you "have to" answer the questions. Deprioritize.
> * Back button is very important to preserve the user's freedom throughout the app so it should be prioritized
> * Going back to home page is not a usability critical since there's nothing on the home page the user needs to access when they are doing the diary. However still necessary since we don't have a tab bar to let them clear out the navigation stack.

1. "X" on the top at the top: 
- We can have it since we should allow users to temporarily quit the survey and continue doing it later.

2. "Skip" meaning:
- This is my concern as well, does the "skip" have the same meaning as "I don't want to answer this question"? In terms of the result and the purpose of the action, it does. I think this deprioritizes the option of "not willing to answer".

**Comment by yago1994** [comment]
Sounds great, agreed!

**Comment by JayceKongg** [comment]
### Reopen this issue to update when the user "skip" a question, what happens on the summary page

In order to use the same format for "Completed" and "Incomplete" questions, we can use color to distinguish them. For example, on the summary page, we can use blue to highlight questions with data and gray for questions without data (a bit opposite since we might want to highlight "Incomplete Questions"). It works but if users can't add or change the answers, the summary page isn't important. **How about we disable the "skip" and focus on other problems?** @yago1994 

Figma link: 
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4940%3A46036&mode=design&t=Qv6UmVodHfh9YowZ-1](url)

<img width="1650" alt="Screenshot 2023-10-05 at 19 21 59" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/69c66cff-04df-4a43-88e0-ffb7cc2ae3fb">
<img width="1650" alt="Screenshot 2023-10-05 at 19 22 28" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/df753f46-df43-4898-88f5-5f04447a0efd">

**Comment by yago1994** [comment]
This determination sounds good to me. 

Remove Skip and void headaches. Will update issue for you @Naomi-Nyama
