### ISSUE TITLE
Test Update

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#82]
# Goal
Test persistence of the audio files after an update

## To Test
- Go from 1.0 (5) to another version using same data scheme

## Current notes
- Updating from 1.0 (4) to (5) causes errors on Home and Diary tabs. Possible conflict with Cubits. 
-

**Comment by MorganGreenleaf-Emory** [comment]
Should test on IOS and Android both

**Comment by Wiza-Munthali** [comment]
@yago1994 @MorganGreenleaf-Emory 

After running some tests and reading a bunch of articles, I have come to the conclusion that ObjectBox nor the Cubits are at fault (as initially suspected).

**FYI** : Cubits are not responsible for any business logic, Cubits are the equivalent to viewmodels in MVVM where they dictate the UI based on the information passed by the user or the database/backend.

As I mentioned last time every time the application gets updated the ID of the application changes automatically on the systems level (only in iOS). Hence why when we save the path to the recordings in the database it saves it with the application ID so it looks something like this: "/var/mobile/Containers/Data/Application/**_565DA310-8B3E-4E66-A148-AC95F94F89DB_**/Documents/recordings/audio_prompt_12_2023-10-25-10-56-13.mp3)".

now when we are trying to retrieve that recording (after updating the app) it doesn't exist anymore because the applications ID (565DA310-8B3E-4E66-A148-AC95F94F89DB) has been changed by the system (because of the update).

## Solution
The tried and tested solution 

We only save the name of the recording in the database and dynamically create the path to the recording with the directory path of the internal storage.

### Saving Recordings
```
final file = await changeFileName(url); // Change file from aac to mp3
final name = p.basename(file.path); // get the name and extension - recording.mp3
widget.onSave?.call(name); // Only saving the name
```

### Retrieving Recordings
```
final directory = await getApplicationDocumentsDirectory(); // Getting internal storage directory
final path = p.join(directory.path, 'recordings', recording.name); // creating the path to the recording dynamically
```

**Comment by yago1994** [comment]
This is great @Wiza-Munthali thanks for the detailed explanation. This makes sense based on the previous conversations we had around the audio file disappearing or not being saved in iOS. Seems like a simple and elegant solution 👍🚀
